server:
  port: 80
spring:
  main:
    banner-mode: 'off'
  jackson:
    time-zone: GMT+8
  datasource:
    first:
      type: com.zaxxer.hikari.HikariDataSource
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://192.168.130.88:3306/test?autoReconnect=true&autoReconnectForPools=true&allowMultiQueries=true&useUnicode=true&characterEncoding=utf8&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai
      username: root
      password: root123
      minimum-idle: 5
      # 空闲连接存活最大时间，默认600000（10分钟）
      idle-timeout: 180000
      # 连接池最大连接数，默认是10
      maximum-pool-size: 10
      # 此属性控制从池返回的连接的默认自动提交行为,默认值：true
      auto-commit: true
      # 连接池名称
      pool-name: MyHikariCP-1
      # 此属性控制池中连接的最长生命周期，值0表示无限生命周期，默认1800000即30分钟
      max-lifetime: 1800000
      # 数据库连接超时时间,默认30秒，即30000
      connection-timeout: 30000
      connection-test-query: SELECT 1

    second:
      type: com.zaxxer.hikari.HikariDataSource
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://192.168.130.88:3306/test?autoReconnect=true&autoReconnectForPools=true&allowMultiQueries=true&useUnicode=true&characterEncoding=utf8&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai
      username: root
      password: root123
      minimum-idle: 5
      idle-timeout: 180000
      maximum-pool-size: 10
      auto-commit: true
      pool-name: MyHikariCP-2
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1

  redis:
    host: 192.168.130.88
    port: 6379
    password: 123

  rabbitmq:
    username: admin
    password: 123
    host: 192.168.130.88
    port: 5672
    virtual-host: /
    listener:
      simple:
        acknowledge-mode: manual

  http:
    converters:
      preferred-json-mapper: jackson

swagger:
  enabled: true
  title: springboot api文档
  description: springboot api文档
  version: 1.0.0
  basePackage: com.nei.controller

logging:
  level:
    com.nei.mapper: debug
